### ISSUE TITLE
Vicon Dependency Out of Date

### ISSUE THREAD

**Issue by ajlewis02** [WPI-AIM/AIM_GaitAnalysisToolkit#5]
Vicon Dependency is listed as Vicon @ 8d53bf5 - a few commits out of date

**Comment by nag92** [comment]
Can you show me a screen shot of where you are seeing this? I don't see a specified commit in the submodule

**Comment by ajlewis02** [comment]
![image](https://user-images.githubusercontent.com/59977298/83167149-dfbacf80-a0dd-11ea-8fe3-cbed86602fd5.png)

Specifically, the Vicon dependency is listed as being at commit 8d53bf5, which corresponds to the first pull request in Vicon.

**Comment by nag92** [comment]
got it, I will merge a commit soon.
